7# -*- coding: utf-8 -*-
"""
All the main models and architectures used as classes. This code is planned for NEST 3.2

"""
import nest
import numpy as np
import pandas as pd
import os, sys
import time
sys.path.append(os.path.dirname(__file__))
import tools
nest.Install('mymodule3')
# nest.Install('mymoduleSOM')


class ExcInhNetwork(object):
    def __init__(self, params, installmod=False):
        # Parameters of the network
        self.server = params['server']
        self.multimeter = None
        self.ispikes = None
        self.espikes = None
        self.N_exc = params['N_exc']  # number of excitatory neurons
        self.N_inh = params['N_inh']  # number of inhibitory neurons
        self.P = params['P']  # probability of connection
        self.extent = params['extent']  # Spatial extent of the network (mm)
        self.latency = params['latency']
        self.autapse = params['autapse']
        self.multapse = params['multapse']

        # Synaptic conductances
        self.exc_exc_recurrent = params["exc_exc_recurrent"]  # nS
        self.exc_inh_recurrent = params["exc_inh_recurrent"]  # nS
        self.inh_inh_recurrent = params["inh_inh_recurrent"]  # nS
        self.inh_exc_recurrent = params["inh_exc_recurrent"]  # nS
        self.th_exc_external   = params["th_exc_external"]  # nS
        self.th_inh_external   = params["th_inh_external"]  # nS
        self.cc_exc_external   = params["cc_exc_external"]  # nS
        self.cc_inh_external   = params["cc_inh_external"]  # nS

        # Parameters of the neuron models
        self.Excitatory_cell_params = {
            "V_th": params["exc_V_th"],  # mV
            "V_reset": params["exc_V_reset"],  # mV
            "t_ref": params["exc_t_ref"],  # ms
            "g_L": params["exc_g_L"],  # nS
            "C_m": params["exc_C_m"],  # pF
            "E_ex": params["exc_E_ex"],  # mV
            "E_in": params["exc_E_in"],  # mV
            "E_L": params["exc_E_L"],  # mV
            "tau_rise_AMPA": params["exc_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["exc_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["exc_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["exc_tau_decay_GABA_A"],  # ms
            "tau_m": params["exc_tau_m"],  # ms
            "I_e": params["exc_I_e"]  # pA
        }

        self.Inhibitory_cell_params = {
            "V_th": params["inh_V_th"],  # mV
            "V_reset": params["inh_V_reset"],  # mV
            "t_ref": params["inh_t_ref"],  # ms
            "g_L": params["inh_g_L"],  # nS
            "C_m": params["inh_C_m"],  # pF
            "E_ex": params["inh_E_ex"],  # mV
            "E_in": params["inh_E_in"],  # mV
            "E_L": params["inh_E_L"],  # mV
            "tau_rise_AMPA": params["inh_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["inh_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["inh_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["inh_tau_decay_GABA_A"],  # ms
            "tau_m": params["inh_tau_m"],  # ms
            "I_e": params["inh_I_e"]  # pA
        }

        # Parameters of the simulation
        self.simtime = params["simtime"]  # ms
        self.simstep = params["simstep"]  # ms
        self.warmup  = params["warmup"]
        self.num_threads = params["num_threads"]  # Number of threads
        # False = to file

        # The external input generated by a Poisson process with rate:
        # v_ext(t) = v_signal(t) + n(t),
        # v_signal(t) = A * sin (2 * pi * f *t) + v_0,
        # n(t) is generated by an Ornstein-Uhlenbeck process
        self.n_ext = params["n_ext"]  # number of external neurons
        self.v_0 = params["v_0"]  # constant rate of the external neurons
        self.A_ext = params["A_ext"]  # Amplitude (spikes/ms)
        self.f_ext = params["f_ext"]  # Frequency (Hz)
        self.ou_sigma = params["ou_sigma"]  # Standard deviation of n(t) (spike/ms)
        self.ou_tau = params["ou_tau"]  # Time constant of n(t) (ms)


        # Parameters for the analysis of results
        self.recstep = params["recstep"]
        self.To_be_measured = params["To_be_measured"]  # String with
        # properties of the subthreshold response that will be recorded among
        # 'V_m', 'g_ex','g_in'.


    def create_network(self):
        """
        """
        nest.ResetKernel()
        nest.overwrite_files = True
        np.random.seed(int(time.time()))
        seed = int(time.time() * 100) % 2 ** 32  # Seeds
        nest.SetKernelStatus({"local_num_threads": self.num_threads,
                              "resolution": self.simstep,
                              "data_path": os.path.abspath(os.path.join(__file__, "../data/backend")),
                              "rng_seed": seed})

        nest.CopyModel("iaf_bw_2003", "exc_cell", self.Excitatory_cell_params)
        nest.CopyModel("iaf_bw_2003", "inh_cell", self.Inhibitory_cell_params)

        positions = nest.spatial.free(nest.random.uniform(min=-0.5, max=0.5), num_dimensions=2)
        nodes_ex = nest.Create("exc_cell", self.N_exc, positions=positions)
        nodes_in = nest.Create("inh_cell", self.N_inh, positions=positions)

        # Ornstein-Uhlenbeck process (solved by Euler method)
        time_array = np.arange(self.simstep, self.simtime -
                               self.simstep, self.simstep)
        # ou_n = len(time_array)  # Number of time steps.
        # # Define renormalized variables (to avoid recomputing these constants
        # # at every time step)
        # ou_sigma_bis = self.OU_sigma * np.sqrt(2. / self.OU_tau)
        # ou_sqrtdt = np.sqrt(self.simstep)
        # ou_x = np.zeros(ou_n)  # OU output

        # for i in range(ou_n - 1):
        #     ou_x[i + 1] = ou_x[i] + self.simstep * (-ou_x[i] / self.OU_tau) + \
        #                   ou_sigma_bis * ou_sqrtdt * np.random.randn()
        ou_x = tools.ounoise(len(time_array), self.simstep, self.ou_sigma, self.ou_tau)

        if self.A_ext > 0:
            sin_signal = self.A_ext * np.sin(
                2.0 * np.pi * self.f_ext * time_array / 1000.0) + self.v_0
            noise_thex = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
            noise_thin = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
        else:
            noise_thex = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
            noise_thin = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
        noise_ccex = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})
        noise_ccin = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})

        # parrot_th = nest.Create("parrot_neuron", self.N_exc + self.N_inh)
        # parrot_cc = nest.Create("parrot_neuron", self.N_exc + self.N_inh)

        self.espikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        self.ispikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})

        self.multimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.multimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])

        if self.latency < self.simstep:
            self.latency = self.simstep

        nest.CopyModel("static_synapse", "exc_exc_recurrent",
                       {"weight": self.exc_exc_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "exc_inh_recurrent",
                       {"weight": self.exc_inh_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "inh_inh_recurrent",
                       {"weight": self.inh_inh_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "inh_exc_recurrent",
                       {"weight": self.inh_exc_recurrent,
                        "delay": self.latency})

        nest.CopyModel("static_synapse", "th_exc_external",
                       {"weight": self.th_exc_external})
        nest.CopyModel("static_synapse", "th_inh_external",
                       {"weight": self.th_inh_external})
        nest.CopyModel("static_synapse", "cc_exc_external",
                       {"weight": self.cc_exc_external})
        nest.CopyModel("static_synapse", "cc_inh_external",
                       {"weight": self.cc_inh_external})

        conn_params_recurrent = {'rule': 'pairwise_bernoulli', 'p': self.P, 'use_on_source': True}
        conn_dict = {
            "rule": 'pairwise_bernoulli',
            "p": 0.2,
            "use_on_source": True,
            "allow_autapses": self.autapse,
            "allow_multapses": self.multapse,
            "mask":{'rectangular':{'lower_left':[-.5, -.5], 'upper_right':[.5, .5]}}
        }

        nest.Connect(nodes_ex, nodes_ex, conn_dict, "exc_exc_recurrent")
        nest.Connect(nodes_ex, nodes_in, conn_dict, "exc_inh_recurrent")
        nest.Connect(nodes_in, nodes_ex, conn_dict, "inh_exc_recurrent")
        nest.Connect(nodes_in, nodes_in, conn_dict, "inh_inh_recurrent")

        conn_noise_dict = {'rule': 'fixed_indegree', 'indegree': 1}
        nest.Connect(noise_thex, nodes_ex, conn_noise_dict, "th_exc_external")
        nest.Connect(noise_thin, nodes_in, conn_noise_dict, "th_inh_external")
        nest.Connect(noise_ccex, nodes_ex, conn_noise_dict, "cc_exc_external")
        nest.Connect(noise_ccin, nodes_in, conn_noise_dict, "cc_inh_external")

        nest.Connect(self.multimeter, nodes_ex)
#        nest.Connect(self.multimeter, nodes_in)
        nest.Connect(nodes_ex, self.espikes)
        nest.Connect(nodes_in, self.ispikes)
        return

    def simulate_network(self):
        nest.Simulate(self.simtime)
        mm_pd = pd.DataFrame.from_dict(self.multimeter.get('events'))
        espikes_pd = pd.DataFrame.from_dict(self.espikes.get('events'))
        ispikes_pd = pd.DataFrame.from_dict(self.ispikes.get('events'))
        return [mm_pd, espikes_pd, ispikes_pd]

class ExcInhNetworkrecordboth(object):
    def __init__(self, params, installmod=False):
        # Parameters of the network
        self.server = params['server']
        self.emultimeter = None
        self.imultimeter = None
        self.ispikes = None
        self.espikes = None
        self.extspikes = None
        self.N_exc = params['N_exc']  # number of excitatory neurons
        self.N_inh = params['N_inh']  # number of inhibitory neurons
        self.P = params['P']  # probability of connection
        self.extent = params['extent']  # Spatial extent of the network (mm)
        self.latency = params['latency']
        self.autapse = params['autapse']
        self.multapse = params['multapse']

        # Synaptic conductances
        self.exc_exc_recurrent = params["exc_exc_recurrent"]  # nS
        self.exc_inh_recurrent = params["exc_inh_recurrent"]  # nS
        self.inh_inh_recurrent = params["inh_inh_recurrent"]  # nS
        self.inh_exc_recurrent = params["inh_exc_recurrent"]  # nS
        self.th_exc_external   = params["th_exc_external"]  # nS
        self.th_inh_external   = params["th_inh_external"]  # nS
        self.cc_exc_external   = params["cc_exc_external"]  # nS
        self.cc_inh_external   = params["cc_inh_external"]  # nS

        # Parameters of the neuron models
        self.Excitatory_cell_params = {
            "V_th": params["exc_V_th"],  # mV
            "V_reset": params["exc_V_reset"],  # mV
            "t_ref": params["exc_t_ref"],  # ms
            "g_L": params["exc_g_L"],  # nS
            "C_m": params["exc_C_m"],  # pF
            "E_ex": params["exc_E_ex"],  # mV
            "E_in": params["exc_E_in"],  # mV
            "E_L": params["exc_E_L"],  # mV
            "tau_rise_AMPA": params["exc_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["exc_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["exc_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["exc_tau_decay_GABA_A"],  # ms
            "tau_m": params["exc_tau_m"],  # ms
            "I_e": params["exc_I_e"]  # pA
        }

        self.Inhibitory_cell_params = {
            "V_th": params["inh_V_th"],  # mV
            "V_reset": params["inh_V_reset"],  # mV
            "t_ref": params["inh_t_ref"],  # ms
            "g_L": params["inh_g_L"],  # nS
            "C_m": params["inh_C_m"],  # pF
            "E_ex": params["inh_E_ex"],  # mV
            "E_in": params["inh_E_in"],  # mV
            "E_L": params["inh_E_L"],  # mV
            "tau_rise_AMPA": params["inh_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["inh_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["inh_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["inh_tau_decay_GABA_A"],  # ms
            "tau_m": params["inh_tau_m"],  # ms
            "I_e": params["inh_I_e"]  # pA
        }

        # Parameters of the simulation
        self.simtime = params["simtime"]  # ms
        self.simstep = params["simstep"]  # ms
        self.warmup  = params["warmup"]
        self.num_threads = params["num_threads"]  # Number of threads
        # False = to file

        # The external input generated by a Poisson process with rate:
        # v_ext(t) = v_signal(t) + n(t),
        # v_signal(t) = A * sin (2 * pi * f *t) + v_0,
        # n(t) is generated by an Ornstein-Uhlenbeck process
        self.n_ext = params["n_ext"]  # number of external neurons
        self.v_0 = params["v_0"]  # constant rate of the external neurons
        self.A_ext = params["A_ext"]  # Amplitude (spikes/ms)
        self.f_ext = params["f_ext"]  # Frequency (Hz)
        self.ou_sigma = params["ou_sigma"]  # Standard deviation of n(t) (spike/ms)
        self.ou_tau = params["ou_tau"]  # Time constant of n(t) (ms)


        # Parameters for the analysis of results
        self.recstep = params["recstep"]
        self.To_be_measured = params["To_be_measured"]  # String with
        # properties of the subthreshold response that will be recorded among
        # 'V_m', 'g_ex','g_in'.


    def create_network(self):
        """
        """
        nest.ResetKernel()
        nest.overwrite_files = True
        np.random.seed(int(time.time()))
        seed = int(time.time() * 100) % 2 ** 32  # Seeds
        nest.SetKernelStatus({"local_num_threads": self.num_threads,
                              "resolution": self.simstep,
                              "data_path": os.path.abspath(os.path.join(__file__, "../data/backend")),
                              "rng_seed": seed})

        nest.CopyModel("iaf_bw_2003", "exc_cell", self.Excitatory_cell_params)
        nest.CopyModel("iaf_bw_2003", "inh_cell", self.Inhibitory_cell_params)

        positions = nest.spatial.free(nest.random.uniform(min=-0.5, max=0.5), num_dimensions=2)
        nodes_ex = nest.Create("exc_cell", self.N_exc, positions=positions)
        nodes_in = nest.Create("inh_cell", self.N_inh, positions=positions)

        # Ornstein-Uhlenbeck process (solved by Euler method)
        time_array = np.arange(self.simstep, self.simtime -
                               self.simstep, self.simstep)
        # ou_n = len(time_array)  # Number of time steps.
        # # Define renormalized variables (to avoid recomputing these constants
        # # at every time step)
        # ou_sigma_bis = self.OU_sigma * np.sqrt(2. / self.OU_tau)
        # ou_sqrtdt = np.sqrt(self.simstep)
        # ou_x = np.zeros(ou_n)  # OU output

        # for i in range(ou_n - 1):
        #     ou_x[i + 1] = ou_x[i] + self.simstep * (-ou_x[i] / self.OU_tau) + \
        #                   ou_sigma_bis * ou_sqrtdt * np.random.randn()
        ou_x = tools.ounoise(len(time_array), self.simstep, self.ou_sigma, self.ou_tau)

        if self.A_ext > 0:
            sin_signal = self.A_ext * np.sin(
                2.0 * np.pi * self.f_ext * time_array / 1000.0) + self.v_0
            noise_thex = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
            noise_thin = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
        else:
            noise_thex = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
            noise_thin = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
        noise_ccex = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})
        noise_ccin = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})

        # parrot_th = nest.Create("parrot_neuron", self.N_exc + self.N_inh)
        # parrot_cc = nest.Create("parrot_neuron", self.N_exc + self.N_inh)

        self.espikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        self.ispikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        # self.extspikes = nest.Create("spike_recorder")

        self.emultimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.emultimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])
        self.imultimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.imultimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])

        if self.latency < self.simstep:
            self.latency = self.simstep

        nest.CopyModel("static_synapse", "exc_exc_recurrent",
                       {"weight": self.exc_exc_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "exc_inh_recurrent",
                       {"weight": self.exc_inh_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "inh_inh_recurrent",
                       {"weight": self.inh_inh_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "inh_exc_recurrent",
                       {"weight": self.inh_exc_recurrent,
                        "delay": self.latency})

        nest.CopyModel("static_synapse", "th_exc_external",
                       {"weight": self.th_exc_external})
        nest.CopyModel("static_synapse", "th_inh_external",
                       {"weight": self.th_inh_external})
        nest.CopyModel("static_synapse", "cc_exc_external",
                       {"weight": self.cc_exc_external})
        nest.CopyModel("static_synapse", "cc_inh_external",
                       {"weight": self.cc_inh_external})

        conn_params_recurrent = {'rule': 'pairwise_bernoulli', 'p': self.P, 'use_on_source': True}
        conn_dict = {
            "rule": 'pairwise_bernoulli',
            "p": 0.2,
            "use_on_source": True,
            "allow_autapses": self.autapse,
            "allow_multapses": self.multapse,
            "mask":{'rectangular':{'lower_left':[-.5, -.5], 'upper_right':[.5, .5]}}
        }

        nest.Connect(nodes_ex, nodes_ex, conn_dict, "exc_exc_recurrent")
        nest.Connect(nodes_ex, nodes_in, conn_dict, "exc_inh_recurrent")
        nest.Connect(nodes_in, nodes_ex, conn_dict, "inh_exc_recurrent")
        nest.Connect(nodes_in, nodes_in, conn_dict, "inh_inh_recurrent")

        conn_noise_dict = {'rule': 'fixed_indegree', 'indegree': 1}
        nest.Connect(noise_thex, nodes_ex, conn_noise_dict, "th_exc_external")
        nest.Connect(noise_thin, nodes_in, conn_noise_dict, "th_inh_external")
        nest.Connect(noise_ccex, nodes_ex, conn_noise_dict, "cc_exc_external")
        nest.Connect(noise_ccin, nodes_in, conn_noise_dict, "cc_inh_external")

        nest.Connect(self.emultimeter, nodes_ex)
        nest.Connect(self.imultimeter, nodes_in)
        nest.Connect(nodes_ex, self.espikes)
        nest.Connect(nodes_in, self.ispikes)
        #nest.Connect(noise_thex, self.extspikes)
        #nest.Connect(noise_thin, self.extspikes)
        #nest.Connect(noise_ccex, self.extspikes)
        #nest.Connect(noise_ccin, self.extspikes)

        return

    def simulate_network(self):
        nest.Simulate(self.simtime)
        emm_pd = pd.DataFrame.from_dict(self.emultimeter.get('events'))
        imm_pd = pd.DataFrame.from_dict(self.imultimeter.get('events'))
        espikes_pd = pd.DataFrame.from_dict(self.espikes.get('events'))
        ispikes_pd = pd.DataFrame.from_dict(self.ispikes.get('events'))
        # extspikes_pd = pd.DataFrame.from_dict(self.extspikes.get('events'))
        return [emm_pd, imm_pd, espikes_pd, ispikes_pd]


class ExcInhNetworkrecordrecurrent(object):
    def __init__(self, params, installmod=False):
        # Parameters of the network
        self.server = params['server']
        self.emultimeter = None
        self.imultimeter = None
        self.ispikes = None
        self.espikes = None
        self.extspikes = None
        self.N_exc = params['N_exc']  # number of excitatory neurons
        self.N_inh = params['N_inh']  # number of inhibitory neurons
        self.P = params['P']  # probability of connection
        self.extent = params['extent']  # Spatial extent of the network (mm)
        self.latency = params['latency']
        self.autapse = params['autapse']
        self.multapse = params['multapse']

        # Synaptic conductances
        self.exc_exc_recurrent = params["exc_exc_recurrent"]  # nS
        self.exc_inh_recurrent = params["exc_inh_recurrent"]  # nS
        self.inh_inh_recurrent = params["inh_inh_recurrent"]  # nS
        self.inh_exc_recurrent = params["inh_exc_recurrent"]  # nS
        self.th_exc_external   = params["th_exc_external"]  # nS
        self.th_inh_external   = params["th_inh_external"]  # nS
        self.cc_exc_external   = params["cc_exc_external"]  # nS
        self.cc_inh_external   = params["cc_inh_external"]  # nS

        # Parameters of the neuron models
        self.Excitatory_cell_params = {
            "V_th": params["exc_V_th"],  # mV
            "V_reset": params["exc_V_reset"],  # mV
            "t_ref": params["exc_t_ref"],  # ms
            "g_L": params["exc_g_L"],  # nS
            "C_m": params["exc_C_m"],  # pF
            "E_ex": params["exc_E_ex"],  # mV
            "E_in": params["exc_E_in"],  # mV
            "E_L": params["exc_E_L"],  # mV
            "tau_rise_AMPA": params["exc_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["exc_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["exc_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["exc_tau_decay_GABA_A"],  # ms
            "tau_m": params["exc_tau_m"],  # ms
            "I_e": params["exc_I_e"]  # pA
        }

        self.Inhibitory_cell_params = {
            "V_th": params["inh_V_th"],  # mV
            "V_reset": params["inh_V_reset"],  # mV
            "t_ref": params["inh_t_ref"],  # ms
            "g_L": params["inh_g_L"],  # nS
            "C_m": params["inh_C_m"],  # pF
            "E_ex": params["inh_E_ex"],  # mV
            "E_in": params["inh_E_in"],  # mV
            "E_L": params["inh_E_L"],  # mV
            "tau_rise_AMPA": params["inh_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["inh_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["inh_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["inh_tau_decay_GABA_A"],  # ms
            "tau_m": params["inh_tau_m"],  # ms
            "I_e": params["inh_I_e"]  # pA
        }

        # Parameters of the simulation
        self.simtime = params["simtime"]  # ms
        self.simstep = params["simstep"]  # ms
        self.warmup  = params["warmup"]
        self.num_threads = params["num_threads"]  # Number of threads
        # False = to file

        # The external input generated by a Poisson process with rate:
        # v_ext(t) = v_signal(t) + n(t),
        # v_signal(t) = A * sin (2 * pi * f *t) + v_0,
        # n(t) is generated by an Ornstein-Uhlenbeck process
        self.n_ext = params["n_ext"]  # number of external neurons
        self.v_0 = params["v_0"]  # constant rate of the external neurons
        self.A_ext = params["A_ext"]  # Amplitude (spikes/ms)
        self.f_ext = params["f_ext"]  # Frequency (Hz)
        self.ou_sigma = params["ou_sigma"]  # Standard deviation of n(t) (spike/ms)
        self.ou_tau = params["ou_tau"]  # Time constant of n(t) (ms)


        # Parameters for the analysis of results
        self.recstep = params["recstep"]
        self.To_be_measured = params["To_be_measured"]  # String with
        # properties of the subthreshold response that will be recorded among
        # 'V_m', 'g_ex','g_in'.


    def create_network(self):
        """
        """
        nest.ResetKernel()
        nest.overwrite_files = True
        np.random.seed(int(time.time()))
        seed = int(time.time() * 100) % 2 ** 32  # Seeds
        nest.SetKernelStatus({"local_num_threads": self.num_threads,
                              "resolution": self.simstep,
                              "data_path": os.path.abspath(os.path.join(__file__, "../data/backend")),
                              "rng_seed": seed})

        nest.CopyModel("iaf_bw_2003", "exc_cell", self.Excitatory_cell_params)
        nest.CopyModel("iaf_bw_2003", "inh_cell", self.Inhibitory_cell_params)
        nest.CopyModel("iaf_bw_2003", "record_cell", tools.dictupdate(self.Excitatory_cell_params, {'V_th': 5e5}))


        positions = nest.spatial.free(nest.random.uniform(min=-0.5, max=0.5), num_dimensions=2)
        nodes_ex = nest.Create("exc_cell", self.N_exc, positions=positions)
        nodes_in = nest.Create("inh_cell", self.N_inh, positions=positions)
        node_record = nest.Create("exc_cell", 1, positions=positions)

        # Ornstein-Uhlenbeck process (solved by Euler method)
        time_array = np.arange(self.simstep, self.simtime -
                               self.simstep, self.simstep)
        # ou_n = len(time_array)  # Number of time steps.
        # # Define renormalized variables (to avoid recomputing these constants
        # # at every time step)
        # ou_sigma_bis = self.OU_sigma * np.sqrt(2. / self.OU_tau)
        # ou_sqrtdt = np.sqrt(self.simstep)
        # ou_x = np.zeros(ou_n)  # OU output

        # for i in range(ou_n - 1):
        #     ou_x[i + 1] = ou_x[i] + self.simstep * (-ou_x[i] / self.OU_tau) + \
        #                   ou_sigma_bis * ou_sqrtdt * np.random.randn()
        ou_x = tools.ounoise(len(time_array), self.simstep, self.ou_sigma, self.ou_tau)

        if self.A_ext > 0:
            sin_signal = self.A_ext * np.sin(
                2.0 * np.pi * self.f_ext * time_array / 1000.0) + self.v_0
            noise_thex = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
            noise_thin = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
        else:
            noise_thex = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
            noise_thin = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
        noise_ccex = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})
        noise_ccin = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})

        # parrot_th = nest.Create("parrot_neuron", self.N_exc + self.N_inh)
        # parrot_cc = nest.Create("parrot_neuron", self.N_exc + self.N_inh)

        self.espikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        self.ispikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        self.recurrspikes = nest.Create("spike_recorder")

        conn_dict = {
            "rule": 'pairwise_bernoulli',
            "p": 0.2,
            "use_on_source": True,
            "allow_autapses": self.autapse,
            "allow_multapses": self.multapse,
            "mask":{'rectangular':{'lower_left':[-.5, -.5], 'upper_right':[.5, .5]}}
        }
        # self.extspikes = nest.Create("spike_recorder")

        self.emultimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.emultimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])
        self.recurrmultimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.recurrmultimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])

        if self.latency < self.simstep:
            self.latency = self.simstep

        nest.CopyModel("static_synapse", "exc_exc_recurrent",
                       {"weight": self.exc_exc_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "exc_inh_recurrent",
                       {"weight": self.exc_inh_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "inh_inh_recurrent",
                       {"weight": self.inh_inh_recurrent,
                        "delay": self.latency})
        nest.CopyModel("static_synapse", "inh_exc_recurrent",
                       {"weight": self.inh_exc_recurrent,
                        "delay": self.latency})

        nest.CopyModel("static_synapse", "th_exc_external",
                       {"weight": self.th_exc_external})
        nest.CopyModel("static_synapse", "th_inh_external",
                       {"weight": self.th_inh_external})
        nest.CopyModel("static_synapse", "cc_exc_external",
                       {"weight": self.cc_exc_external})
        nest.CopyModel("static_synapse", "cc_inh_external",
                       {"weight": self.cc_inh_external})

        conn_params_recurrent = {'rule': 'pairwise_bernoulli', 'p': self.P, 'use_on_source': True}
        conn_dict = {
            "rule": 'pairwise_bernoulli',
            "p": 0.2,
            "use_on_source": True,
            "allow_autapses": self.autapse,
            "allow_multapses": self.multapse,
            "mask":{'rectangular':{'lower_left':[-.5, -.5], 'upper_right':[.5, .5]}}
        }

        nest.Connect(nodes_ex, nodes_ex, conn_dict, "exc_exc_recurrent")
        nest.Connect(nodes_ex, nodes_in, conn_dict, "exc_inh_recurrent")
        nest.Connect(nodes_in, nodes_ex, conn_dict, "inh_exc_recurrent")
        nest.Connect(nodes_in, nodes_in, conn_dict, "inh_inh_recurrent")

        nest.Connect(nodes_ex, node_record, conn_dict, "exc_exc_recurrent")
        nest.Connect(nodes_in, node_record, conn_dict, "inh_exc_recurrent")

        conn_noise_dict = {'rule': 'fixed_indegree', 'indegree': 1}
        nest.Connect(noise_thex, nodes_ex, conn_noise_dict, "th_exc_external")
        nest.Connect(noise_thin, nodes_in, conn_noise_dict, "th_inh_external")
        nest.Connect(noise_ccex, nodes_ex, conn_noise_dict, "cc_exc_external")
        nest.Connect(noise_ccin, nodes_in, conn_noise_dict, "cc_inh_external")

        nest.Connect(self.emultimeter, nodes_ex)
        nest.Connect(self.recurrmultimeter, node_record)
        nest.Connect(nodes_ex, self.espikes)
        nest.Connect(nodes_in, self.ispikes)
        nest.Connect(node_record, self.recurrspikes)
        #nest.Connect(noise_thex, self.extspikes)
        #nest.Connect(noise_thin, self.extspikes)
        #nest.Connect(noise_ccex, self.extspikes)
        #nest.Connect(noise_ccin, self.extspikes)

        return

    def simulate_network(self):
        nest.Simulate(self.simtime)
        emm_pd = pd.DataFrame.from_dict(self.emultimeter.get('events'))
        recurmm_pd = pd.DataFrame.from_dict(self.recurrmultimeter.get('events'))
        espikes_pd = pd.DataFrame.from_dict(self.espikes.get('events'))
        ispikes_pd = pd.DataFrame.from_dict(self.ispikes.get('events'))
        recurrspikes_pd = pd.DataFrame.from_dict(self.recurrspikes.get('events'))
        # extspikes_pd = pd.DataFrame.from_dict(self.extspikes.get('events'))
        return [emm_pd, recurmm_pd, espikes_pd, ispikes_pd, recurrspikes_pd]


class ExcInhNetworkNEST(object):
    def __init__(self, params):
        # nest.Install('mymoduleSOM')
        # Parameters of the network
        self.emultimeter = None
        self.imultimeter = None
        self.espikes = None
        self.ispikes = None
        self.N_pyr = params['N_pyr']  # number of excitatory neurons
        self.N_pv = params['N_pv']    # number of inhibitory neurons

        self.latency = params['latency']
        self.P = params['P']

        # Synaptic conductances
        self.recurrent_conductances = params["recurrent_conductances"]
        self.external_conductances  = params["thalamic_conductances"]
        self.cortical_conductances  = params["cortical_conductances"]

        # Parameters of the neuron models
        self.Pyr_cell_params = {
            "E_L": params["exc_E_L"],  # mV
            "C_m": params["exc_C_m"],
            "t_ref": params["exc_t_ref"],  # ms
            "V_th": params["exc_V_th"],  # mV
            "V_reset": params["exc_V_reset"],  # mV
            "E_ex": params["exc_E_ex"],
            "E_in": params["exc_E_in"],
            "g_L": params["exc_g_L"],  # nS
            "tau_rise_ex": params["exc_tau_rise_ex"],
            "tau_decay_ex": params["exc_tau_decay_ex"],
            "tau_rise_in": params["exc_tau_rise_in"],
            "tau_decay_in": params["exc_tau_decay_in"],
            "I_e": params["exc_I_e"],  # pA
        }
        self.PV_cell_params = {
            "E_L": params["inh_E_L"],  # mV
            "C_m": params["inh_C_m"],
            "t_ref": params["inh_t_ref"],  # ms
            "V_th": params["inh_V_th"],  # mV
            "V_reset": params["inh_V_reset"],  # mV
            "E_ex": params["inh_E_ex"],
            "E_in": params["inh_E_in"],
            "g_L": params["inh_g_L"],  # nS
            "tau_rise_ex": params["inh_tau_rise_ex"],
            "tau_decay_ex": params["inh_tau_decay_ex"],
            "tau_rise_in": params["inh_tau_rise_in"],
            "tau_decay_in": params["inh_tau_decay_in"],
            "I_e": params["inh_I_e"],  # pA
        }


        # Parameters of the simulation
        self.simtime = params["simtime"]  # ms
        self.simstep = params["simstep"]  # ms
        self.num_threads = params["num_threads"]  # Number of threads
        self.toMemory = params["toMemory"]  # True  = record to memory,
                                            # False = to file

        # The external input generated by a Poisson process with rate:
        # v_ext(t) = v_signal(t) + n(t),
        # v_signal(t) = A * sin (2 * pi * f *t) + v_0,
        # n(t) is generated by an Ornstein-Uhlenbeck process
        self.n_ext = params["n_ext"]  # number of external neurons
        self.v_0 = params["v_0"]  # constant rate of the external neurons
        self.A_ext = params["A_ext"]  # Amplitude (spikes/ms)
        self.f_ext = params["f_ext"]  # Frequency (Hz)
        self.ou_sigma = params["ou_sigma"]  # Standard deviation of n(t) (spike/ms)
        self.ou_tau = params["ou_tau"]  # Time constant of n(t) (ms)

        # Parameters for the analysis of results
        self.recstep = params["recstep"]
        self.To_be_measured = params["To_be_measured"]  # String with
        # properties of the subthreshold response that will be recorded among
        # 'V_m', 'g_ex','g_in'.

    def create_network(self):
        """
        """
        nest.ResetKernel()
        nest.overwrite_files = True
        np.random.seed(int(time.time()))
        seed = int(time.time() * 100) % 2 ** 32  # Seeds
        nest.SetKernelStatus({"local_num_threads": self.num_threads,
                              "resolution": self.simstep,
                              "data_path": os.path.abspath(os.path.join(__file__, "../../data/backend")),
                              "rng_seed": seed})

        nest.CopyModel("iaf_cond_beta", "pyr_cell", self.Pyr_cell_params)
        nest.CopyModel("iaf_cond_beta", "pv_cell",  self.PV_cell_params)

        positions = nest.spatial.free(nest.random.uniform(min=-0.5, max=0.5), num_dimensions=2)
        nodes_pyr = nest.Create("pyr_cell", self.N_pyr, positions=positions)
        nodes_pv  = nest.Create("pv_cell",  self.N_pv,  positions=positions)

        nodes = [nodes_pyr, nodes_pv]

        # Ornstein-Uhlenbeck process (solved by Euler method)
        time_array = np.arange(self.simstep, self.simtime -
                               self.simstep, self.simstep)

        ou_x = tools.ounoise(len(time_array), self.simstep, self.ou_sigma, self.ou_tau)

        if self.A_ext > 0:
            sin_signal = self.A_ext * np.sin(
                2.0 * np.pi * self.f_ext * time_array / 1000.0) + self.v_0
            noise_th = nest.Create("inhomogeneous_poisson_generator",
                                   params={"rate_times": time_array,
                                           'rate_values': self.n_ext * sin_signal})
        else:
            noise_th = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})

        noise_cc = nest.Create("inhomogeneous_poisson_generator",
                               params={"rate_times": time_array,
                                       'rate_values': self.n_ext * ou_x})

        self.espikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        self.ispikes = nest.Create("spike_recorder")

        self.emultimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.emultimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])

        self.imultimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.imultimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])

        if self.latency < self.simstep:
            self.latency = self.simstep

            conn_dict = {
                'rule': 'pairwise_bernoulli',
                #"connection_type": "convergent",
                "p": 0.20,
                "use_on_source": True,
                "allow_autapses": False,
                "allow_multapses": False,
                "mask": {'rectangular': {'lower_left': [-.5, -.5], 'upper_right': [.5, .5]}}
            }
            for row, (prob, gsyn) in enumerate(zip(self.P, self.recurrent_conductances)):
                for col, (pb, gs) in enumerate(zip(prob, gsyn)):
                    if pb == 0.:
                        continue
                    # presynaptic exc., postsynaptic exc.
                    syn_dict = {"synapse_model": "static_synapse",
                                "weight": gs, "delay": self.latency}
                    #conn_dict = tools.dictupdate(conn_dict, {"p": pb})
                    #print(f"Prob. {pb}")
                    #print(f"Weight {gs}")
                    #print(f"Node 1")
                    #print(nodes[row])
                    #print(f"Node 2")
                    #print(nodes[col])
                    nest.Connect(nodes[row], nodes[col],
                                 conn_dict, syn_spec=syn_dict)
                                 # return_synapsecollection=True)
                    # nest.Connect(syn_coll.sources(), syn_coll.targ
                    #     "one_to_one", syn_spec = syn_dict)

            for i, nod in enumerate(nodes):
                nest.Connect(noise_th, nod, "all_to_all",
                             {'synapse_model': 'static_synapse',
                              'weight': self.external_conductances[i]}) # self.external_conductances[i]
                nest.Connect(noise_cc, nod, "all_to_all",
                            {'synapse_model': 'static_synapse',
                             'weight': self.cortical_conductances[i]})

            Nsizes = np.array([self.N_pyr, self.N_pv])
            Totsize = np.sum(Nsizes)
            prevpopidx = Totsize - np.cumsum(Nsizes[::-1])
            prevpopidx = prevpopidx[::-1]

            nest.Connect(self.emultimeter, nodes_pyr)
            nest.Connect(self.imultimeter, nodes_pv)
            nest.Connect(nodes_pyr, self.espikes)
            nest.Connect(nodes_pv,  self.ispikes)

        return

    def simulate_network(self):
        nest.Simulate(self.simtime)
        mm_pd = pd.DataFrame.from_dict(self.emultimeter.get('events'))
        mmi_pd = pd.DataFrame.from_dict(self.imultimeter.get('events'))
        espikes_pd = pd.DataFrame.from_dict(self.espikes.get('events'))
        ispikes_pd = pd.DataFrame.from_dict(self.ispikes.get('events'))
        return [mm_pd, mmi_pd, espikes_pd, ispikes_pd]

class ExcInhNetworkSynFailure(object):
    def __init__(self, params, installmod=False):
        # Parameters of the network
        self.server = params['server']
        self.multimeter = None
        self.ispikes = None
        self.espikes = None
        self.N_exc = params['N_exc']  # number of excitatory neurons
        self.N_inh = params['N_inh']  # number of inhibitory neurons
        self.P = params['P']  # probability of connection
        self.synP = params['synP']  # probability of synaptic succes
        self.extent = params['extent']  # Spatial extent of the network (mm)
        self.latency = params['latency']
        self.autapse = params['autapse']
        self.multapse = params['multapse']

        # Synaptic conductances
        self.exc_exc_recurrent = params["exc_exc_recurrent"]  # nS
        self.exc_inh_recurrent = params["exc_inh_recurrent"]  # nS
        self.inh_inh_recurrent = params["inh_inh_recurrent"]  # nS
        self.inh_exc_recurrent = params["inh_exc_recurrent"]  # nS
        self.th_exc_external   = params["th_exc_external"]  # nS
        self.th_inh_external   = params["th_inh_external"]  # nS
        self.cc_exc_external   = params["cc_exc_external"]  # nS
        self.cc_inh_external   = params["cc_inh_external"]  # nS

        # Parameters of the neuron models
        self.Excitatory_cell_params = {
            "V_th": params["exc_V_th"],  # mV
            "V_reset": params["exc_V_reset"],  # mV
            "t_ref": params["exc_t_ref"],  # ms
            "g_L": params["exc_g_L"],  # nS
            "C_m": params["exc_C_m"],  # pF
            "E_ex": params["exc_E_ex"],  # mV
            "E_in": params["exc_E_in"],  # mV
            "E_L": params["exc_E_L"],  # mV
            "tau_rise_AMPA": params["exc_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["exc_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["exc_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["exc_tau_decay_GABA_A"],  # ms
            "tau_m": params["exc_tau_m"],  # ms
            "I_e": params["exc_I_e"]  # pA
        }

        self.Inhibitory_cell_params = {
            "V_th": params["inh_V_th"],  # mV
            "V_reset": params["inh_V_reset"],  # mV
            "t_ref": params["inh_t_ref"],  # ms
            "g_L": params["inh_g_L"],  # nS
            "C_m": params["inh_C_m"],  # pF
            "E_ex": params["inh_E_ex"],  # mV
            "E_in": params["inh_E_in"],  # mV
            "E_L": params["inh_E_L"],  # mV
            "tau_rise_AMPA": params["inh_tau_rise_AMPA"],  # ms
            "tau_decay_AMPA": params["inh_tau_decay_AMPA"],  # ms
            "tau_rise_GABA_A": params["inh_tau_rise_GABA_A"],  # ms
            "tau_decay_GABA_A": params["inh_tau_decay_GABA_A"],  # ms
            "tau_m": params["inh_tau_m"],  # ms
            "I_e": params["inh_I_e"]  # pA
        }

        # Parameters of the simulation
        self.simtime = params["simtime"]  # ms
        self.simstep = params["simstep"]  # ms
        self.warmup  = params["warmup"]
        self.num_threads = params["num_threads"]  # Number of threads
        # False = to file

        # The external input generated by a Poisson process with rate:
        # v_ext(t) = v_signal(t) + n(t),
        # v_signal(t) = A * sin (2 * pi * f *t) + v_0,
        # n(t) is generated by an Ornstein-Uhlenbeck process
        self.n_ext = params["n_ext"]  # number of external neurons
        self.v_0 = params["v_0"]  # constant rate of the external neurons
        self.A_ext = params["A_ext"]  # Amplitude (spikes/ms)
        self.f_ext = params["f_ext"]  # Frequency (Hz)
        self.ou_sigma = params["ou_sigma"]  # Standard deviation of n(t) (spike/ms)
        self.ou_tau = params["ou_tau"]  # Time constant of n(t) (ms)


        # Parameters for the analysis of results
        self.recstep = params["recstep"]
        self.To_be_measured = params["To_be_measured"]  # String with
        # properties of the subthreshold response that will be recorded among
        # 'V_m', 'g_ex','g_in'.


    def create_network(self):
        """
        """
        nest.ResetKernel()
        nest.overwrite_files = True
        np.random.seed(int(time.time()))
        seed = int(time.time() * 100) % 2 ** 32  # Seeds
        nest.SetKernelStatus({"local_num_threads": self.num_threads,
                              "resolution": self.simstep,
                              "data_path": os.path.abspath(os.path.join(__file__, "../data/backend")),
                              "rng_seed": seed})

        nest.CopyModel("iaf_bw_2003", "exc_cell", self.Excitatory_cell_params)
        nest.CopyModel("iaf_bw_2003", "inh_cell", self.Inhibitory_cell_params)

        positions = nest.spatial.free(nest.random.uniform(min=-0.5, max=0.5), num_dimensions=2)
        nodes_ex = nest.Create("exc_cell", self.N_exc, positions=positions)
        nodes_in = nest.Create("inh_cell", self.N_inh, positions=positions)

        # Ornstein-Uhlenbeck process (solved by Euler method)
        time_array = np.arange(self.simstep, self.simtime -
                               self.simstep, self.simstep)
        # ou_n = len(time_array)  # Number of time steps.
        # # Define renormalized variables (to avoid recomputing these constants
        # # at every time step)
        # ou_sigma_bis = self.OU_sigma * np.sqrt(2. / self.OU_tau)
        # ou_sqrtdt = np.sqrt(self.simstep)
        # ou_x = np.zeros(ou_n)  # OU output

        # for i in range(ou_n - 1):
        #     ou_x[i + 1] = ou_x[i] + self.simstep * (-ou_x[i] / self.OU_tau) + \
        #                   ou_sigma_bis * ou_sqrtdt * np.random.randn()
        ou_x = tools.ounoise(len(time_array), self.simstep, self.ou_sigma, self.ou_tau)

        if self.A_ext > 0:
            sin_signal = self.A_ext * np.sin(
                2.0 * np.pi * self.f_ext * time_array / 1000.0) + self.v_0
            noise_thex = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
            noise_thin = nest.Create("inhomogeneous_poisson_generator",
                                     params={"rate_times": time_array,
                                             'rate_values': self.n_ext * sin_signal})
        else:
            noise_thex = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
            noise_thin = nest.Create("poisson_generator", params={"rate": self.n_ext * self.v_0})
        noise_ccex = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})
        noise_ccin = nest.Create("inhomogeneous_poisson_generator",
                                 params={"rate_times": time_array,
                                         'rate_values': self.n_ext * ou_x})

        # parrot_th = nest.Create("parrot_neuron", self.N_exc + self.N_inh)
        # parrot_cc = nest.Create("parrot_neuron", self.N_exc + self.N_inh)

        self.espikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})
        self.ispikes = nest.Create("spike_recorder")  # , params_pablo={'record_to': 'ascii'})

        self.multimeter = nest.Create('multimeter', {'interval': self.recstep})
        self.multimeter.set(record_from=self.To_be_measured.split(","))  # ["V_m","g_ex","g_in"])

        if self.latency < self.simstep:
            self.latency = self.simstep

        nest.CopyModel("bernoulli_synapse", "exc_exc_recurrent",
                       {"weight": self.exc_exc_recurrent,
                        "delay": self.latency,
                        "p_transmit": self.synP})
        nest.CopyModel("bernoulli_synapse", "exc_inh_recurrent",
                       {"weight": self.exc_inh_recurrent,
                        "delay": self.latency,
                        "p_transmit": self.synP})
        nest.CopyModel("bernoulli_synapse", "inh_inh_recurrent",
                       {"weight": self.inh_inh_recurrent,
                        "delay": self.latency,
                        "p_transmit": self.synP})
        nest.CopyModel("bernoulli_synapse", "inh_exc_recurrent",
                       {"weight": self.inh_exc_recurrent,
                        "delay": self.latency,
                        "p_transmit": self.synP})

        nest.CopyModel("static_synapse", "th_exc_external",
                       {"weight": self.th_exc_external})
        nest.CopyModel("static_synapse", "th_inh_external",
                       {"weight": self.th_inh_external})
        nest.CopyModel("static_synapse", "cc_exc_external",
                       {"weight": self.cc_exc_external})
        nest.CopyModel("static_synapse", "cc_inh_external",
                       {"weight": self.cc_inh_external})

        conn_params_recurrent = {'rule': 'pairwise_bernoulli', 'p': self.P, 'use_on_source': True}
        conn_dict = {
            "rule": 'pairwise_bernoulli',
            "p": 0.2,
            "use_on_source": True,
            "allow_autapses": self.autapse,
            "allow_multapses": self.multapse,
            "mask":{'rectangular':{'lower_left':[-.5, -.5], 'upper_right':[.5, .5]}}
        }

        nest.Connect(nodes_ex, nodes_ex, conn_dict, "exc_exc_recurrent")
        nest.Connect(nodes_ex, nodes_in, conn_dict, "exc_inh_recurrent")
        nest.Connect(nodes_in, nodes_ex, conn_dict, "inh_exc_recurrent")
        nest.Connect(nodes_in, nodes_in, conn_dict, "inh_inh_recurrent")

        conn_noise_dict = {'rule': 'fixed_indegree', 'indegree': 1}
        nest.Connect(noise_thex, nodes_ex, conn_noise_dict, "th_exc_external")
        nest.Connect(noise_thin, nodes_in, conn_noise_dict, "th_inh_external")
        nest.Connect(noise_ccex, nodes_ex, conn_noise_dict, "cc_exc_external")
        nest.Connect(noise_ccin, nodes_in, conn_noise_dict, "cc_inh_external")

        nest.Connect(self.multimeter, nodes_ex)
#        nest.Connect(self.multimeter, nodes_in)
        nest.Connect(nodes_ex, self.espikes)
        nest.Connect(nodes_in, self.ispikes)
        return

    def simulate_network(self):
        nest.Simulate(self.simtime)
        mm_pd = pd.DataFrame.from_dict(self.multimeter.get('events'))
        espikes_pd = pd.DataFrame.from_dict(self.espikes.get('events'))
        ispikes_pd = pd.DataFrame.from_dict(self.ispikes.get('events'))
        return [mm_pd, espikes_pd, ispikes_pd]


params_pablo = {
    "server": "MatiRovereto",
    "label": "Pablo",
    "trials": 5,
    "N_exc": int(4000.0),
    "N_inh": int(1000.0),
    "P": 0.2,
    "n_ext": 800,
    "extent": 1.0,
    "latency": 1.,
    "autapse": False,
    "multapse": False,
    "exc_exc_recurrent": 0.178,
    "exc_inh_recurrent": 0.233,
    "inh_inh_recurrent": -2.70,
    "inh_exc_recurrent": -2.01,
    "th_exc_external": 0.234,
    "th_inh_external": 0.317,
    "cc_exc_external": 0.187,
    "cc_inh_external": 0.254,
    "exc_V_th": -52.0,
    "exc_V_reset": -59.0,
    "exc_t_ref": 2.0,
    "exc_g_L": 25.0,
    "exc_C_m": 500.0,
    "exc_E_ex": 0.0,
    "exc_E_in": -80.0,
    "exc_E_L": -70.0,
    "exc_tau_rise_AMPA": 0.4,
    "exc_tau_decay_AMPA": 2.0,
    "exc_tau_rise_GABA_A": 0.25,
    "exc_tau_decay_GABA_A": 5.0,
    "exc_tau_m": 20.0,
    "exc_I_e": 0.0,
    "inh_V_th": -52.0,
    "inh_V_reset": -59.0,
    "inh_t_ref": 1.0,
    "inh_g_L": 20.0,
    "inh_C_m": 200.0,
    "inh_E_ex": 0.0,
    "inh_E_in": -80.0,
    "inh_E_L": -70.0,
    "inh_tau_rise_AMPA": 0.2,
    "inh_tau_decay_AMPA": 1.0,
    "inh_tau_rise_GABA_A": 0.25,
    "inh_tau_decay_GABA_A": 5.0,
    "inh_tau_m": 10.0,
    "inh_I_e": 0.0,
    "simtime": 2500.0,
    "simstep": .1,
    "recstep": .1,
    "decim_factor": 2,
    "warmup": 500.,
    "siminterval": 2500.0,
    "num_threads": 56,
    "v_0": 1.5,
    "A_ext": 0.0,
    "f_ext": 0.0,
    "ou_sigma": 0.4,
    "ou_tau": 16.0,
    "To_be_measured": 'V_m,g_ex,g_in',
}
params_pablosynfailure = {
    "server": "MatiRovereto",
    "label": "Pablo",
    "trials": 5,
    "N_exc": int(4000.0),
    "N_inh": int(1000.0),
    "P": 0.2,
    "synP": 0.5,
    "n_ext": 800,
    "extent": 1.0,
    "latency": 1.,
    "autapse": False,
    "multapse": False,
    "exc_exc_recurrent": 0.178,
    "exc_inh_recurrent": 0.233,
    "inh_inh_recurrent": -2.70,
    "inh_exc_recurrent": -2.01,
    "th_exc_external": 0.234,
    "th_inh_external": 0.317,
    "cc_exc_external": 0.187,
    "cc_inh_external": 0.254,
    "exc_V_th": -52.0,
    "exc_V_reset": -59.0,
    "exc_t_ref": 2.0,
    "exc_g_L": 25.0,
    "exc_C_m": 500.0,
    "exc_E_ex": 0.0,
    "exc_E_in": -80.0,
    "exc_E_L": -70.0,
    "exc_tau_rise_AMPA": 0.4,
    "exc_tau_decay_AMPA": 2.0,
    "exc_tau_rise_GABA_A": 0.25,
    "exc_tau_decay_GABA_A": 5.0,
    "exc_tau_m": 20.0,
    "exc_I_e": 0.0,
    "inh_V_th": -52.0,
    "inh_V_reset": -59.0,
    "inh_t_ref": 1.0,
    "inh_g_L": 20.0,
    "inh_C_m": 200.0,
    "inh_E_ex": 0.0,
    "inh_E_in": -80.0,
    "inh_E_L": -70.0,
    "inh_tau_rise_AMPA": 0.2,
    "inh_tau_decay_AMPA": 1.0,
    "inh_tau_rise_GABA_A": 0.25,
    "inh_tau_decay_GABA_A": 5.0,
    "inh_tau_m": 10.0,
    "inh_I_e": 0.0,
    "simtime": 2500.0,
    "simstep": .1,
    "recstep": .1,
    "decim_factor": 2,
    "warmup": 500.,
    "siminterval": 2500.0,
    "num_threads": 56,
    "v_0": 1.5,
    "A_ext": 0.0,
    "f_ext": 0.0,
    "ou_sigma": 0.4,
    "ou_tau": 16.0,
    "To_be_measured": 'V_m,g_ex,g_in',
}
params_pabloNEST = {
    "server": "MatiRovereto",
    "label": "PabloNEST",
    "trials": 5,
    "N_pyr": int(4000.0),
    "N_pv":  int(1000.0),
    "n_ext": 800,
    "P": [[0.2, 0.2],  # From PY
          [0.2, 0.2]], # From PV
    "extent": 1.0,
    "latency": 1.0,
    # Matrix of recurrent synaptic conductances
    #                         to  PY  |  PV
    "recurrent_conductances": [[0.178,   0.233],  # From PY
                               [-2.01,   -2.70]],  # From PV

    # Thalamic input (nS)
    "thalamic_conductances": [0.234, 0.317],
    # Cortico-cortical input (nS)
    "cortical_conductances": [0.187, 0.254],

    "exc_E_L": -70.0,
    "exc_C_m": 500.0,
    "exc_t_ref": 2.0,
    "exc_V_th": -52.0,
    "exc_V_reset": -59.0,
    "exc_E_ex": 0.0,
    "exc_E_in": -80.0,
    "exc_g_L": 25.,
    "exc_tau_rise_ex": 0.4,
    "exc_tau_decay_ex": 2.0,
    "exc_tau_rise_in": .25,
    "exc_tau_decay_in": 5.,
    "exc_I_e": 0.0,

    "inh_E_L": -70.0,
    "inh_C_m": 200.0,
    "inh_t_ref": 1.0,
    "inh_V_th": -52.0,
    "inh_V_reset": -59.0,
    "inh_E_ex": 0.0,
    "inh_E_in": -80.0,
    "inh_g_L": 20.0,
    "inh_tau_rise_ex": 0.2,
    "inh_tau_decay_ex": 1.0,
    "inh_tau_rise_in": .25,
    "inh_tau_decay_in": 5.,
    "inh_I_e": 0.0,

    "experiment_id": "placeholder",
    "simtime": 2500.0,
    "simstep": .05,
    "recstep": 1.,
    "decim_factor": 2,
    "warmup": 500.,
    "num_threads": 56,
    "toMemory": True,
    "decimate": False,
    "computeMP": False,
    "v_0": 1.5,
    "A_ext": 0.0,
    "f_ext": 0.0,
    "opto_freq": 0.0,
    "opto_ampl": 0.0,
    "opto_width": 0.0,
    "opto_frac": 0.0,
    "compute_PSP": False,
    "n_PSP": 20,
    "PSP_pop": 0,
    "ou_sigma": 0.4,
    "ou_tau": 16.0,
    "To_be_measured": 'V_m,g_ex,g_in',
}
